model:
  type: diffusion # dsm and diffusion
  network: dualenc
  hidden_dim: 128
  num_convs: 6
  num_convs_local: 4
  cutoff: 40.0
  mlp_act: relu
  beta_schedule: sigmoid
  beta_start: 1.e-7
  beta_end: 5.e-2
  num_diffusion_timesteps: 100
  edge_order: 3
  edge_encoder: mlp
  smooth_conv: false
  noise: gaussian

train:
  seed: 2021
  batch_size: 64
  val_freq: 500
  max_iters: 3000000
  max_grad_norm: 10000.0
  anneal_power: 2.0
  optimizer:
    type: adam
    lr: 1.e-3
    weight_decay: 0.
    beta1: 0.95
    beta2: 0.999
  scheduler:
    type: plateau
    factor: 0.6
    patience: 10

dataset:
  train: ./data/GEOM/RGD1_correct/train_data_40k.pkl
  val: ./data/GEOM/RGD1_correct/val_data_5k.pkl
  test: ./data/GEOM/RGD1_correct/test_data_1k.pkl